name: build
on:
  push:
  pull_request:
  workflow_dispatch:
permissions: {}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends clang-format-15
      - uses: actions/checkout@v4
      - name: Check code style
        run: |
          mk/format-code.sh
          git diff --exit-code
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32da
          libraries: |
            - source-path: ./
            - name: 'Adafruit BusIO'
    timeout-minutes: 30
  unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          cd ..
          mkdir -p EpoxyDuino AUnit Adafruit_BusIO
          curl -fsLS https://github.com/bxparks/EpoxyDuino/archive/v1.6.0.tar.gz | tar -C EpoxyDuino -xz --strip-components=1
          curl -fsLS https://github.com/bxparks/AUnit/archive/v1.7.1.tar.gz | tar -C AUnit -xz --strip-components=1
          curl -fsLS https://github.com/adafruit/Adafruit_BusIO/archive/1.16.2.tar.gz | tar -C Adafruit_BusIO -xz --strip-components=1
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          ./download.sh
          make -j4
          ./unittest.out
        working-directory: ./unittest
    timeout-minutes: 30
