name: build
on:
  push:
  pull_request:
  workflow_dispatch:
permissions: {}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends clang-format-15
      - uses: actions/checkout@v4
      - name: Check code style
        run: |
          mk/format-code.sh
          git diff --exit-code
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32da
          libraries: |
            - source-path: ./
            - name: Streaming
    timeout-minutes: 30
  unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          cd ..
          mkdir -p EpoxyDuino AUnit Streaming
          curl -fsLS https://github.com/bxparks/EpoxyDuino/archive/v1.6.0.tar.gz | tar -C EpoxyDuino -xz --strip-components=1
          curl -fsLS https://github.com/bxparks/AUnit/archive/v1.7.1.tar.gz | tar -C AUnit -xz --strip-components=1
          curl -fsLS https://github.com/janelia-arduino/Streaming/archive/6.1.1.tar.gz | tar -C Streaming -xz --strip-components=1
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          make -j4
          ./unittest.out
        working-directory: ./unittest
    timeout-minutes: 30
